spring:
  datasource:
#    url: jdbc:mysql://120.48.158.62:3306/db_mediweightloss?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://116.63.8.11:3306/db_mediweightloss?useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://localhost:3306/ks?useUnicode=true&characterEncoding=utf8
    username: db_mediweightloss
    password: Z6BEkrDAsYiNFjTH
    driver-class-name: com.mysql.cj.jdbc.Driver
#开发环境配置
#server:
##服务器的HTTP端口，默认为8080
#  address: 0.0.0.0  #本来没有
#  port: 8080
#  servlet:
##应用的访问路径
#  context-path: /